### ISSUE TITLE
有个问题好奇

### ISSUE THREAD

**Issue by Mingyi** [cnpolitics/fandom-publics#1]
这本书是一个来自大陆的学者用英文写的，然后由志愿者众包翻译组译制成中文。

这么折腾？ 作者本身没有想在内地出版的打算？如果她自己出中文版不是更好？

**Comment by realfish** [comment]
关于中文版翻译及出版的缘起，在〈中文版致谢〉（p. XII）里有简略地描述，可供参考。

**Comment by incurable** [comment]
谢谢关注。在英文世界做教授的华人学者，很少自己翻译自己的书——这是一项非常费功夫（吃力不讨好）的事情。

2016-05-20 7:14 GMT-07:00 Mingyi notifications@github.com:

> 这本书是一个来自大陆的学者用英文写的，然后由志愿者众包翻译组译制成中文。
> 
> 这么折腾？ 作者本身没有想在内地出版的打算？如果她自己出中文版不是更好？
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/cnpolitics/fandom-publics/issues/1

## 

方可成 Fang Kecheng
中文博客：http://www.FangKC.cn http://www.fangkc.cn/
Blog: http://www.FangKC.com http://www.fangkc.com/

**Comment by Mingyi** [comment]
谢谢答疑解惑
